### ISSUE TITLE
PlatformException when running in release mode on Android

### ISSUE THREAD

**Issue by Svet-00** [MadBrains/Mad-Pay-Flutter#11]
I copied your code from the example folder and tried to run it on a real device (Pixel 3a, Android 11). In debug mode everything works fine, but in release mode I got the following runtime error:

```
PlatformException(error, Field environment_ for g.a.a.x not found. Known fields are [private int g.a.a.x.e, private static final g.a.a.x g.a.a.x.f, private static volatile b.b.c.a1 g.a.a.x.g], null, java.lang.RuntimeException: Field environment_ for g.a.a.x not found. Known fields are [private int g.a.a.x.e, private static final g.a.a.x g.a.a.x.f, private static volatile b.b.c.a1 g.a.a.x.g]
I/flutter ( 1527):    at b.b.c.v0.a(Unknown Source:72)
I/flutter ( 1527):     at b.b.c.v0.a(Unknown Source:655)
I/flutter ( 1527):     at b.b.c.v0.a(Unknown Source:12)
I/flutter ( 1527):     at b.b.c.k0.a(Unknown Source:60)
I/flutter ( 1527):     at b.b.c.k0.a(Unknown Source:49)
I/flutter ( 1527):     at b.b.c.d1.a(Unknown Source:17)
I/flutter ( 1527):     at b.b.c.d1.a(Unknown Source:4)
I/flutter ( 1527):     at b.b.c.z.a(Unknown Source:12)
I/flutter ( 1527):     at b.b.c.z.a(Unknown Source:6)
I/flutter ( 1527):     at g.a.a.x.a(Unknown Source:2)
I/flutter ( 1527):     at g.a.a.i0.a(Unknown Source:75)
I/flutter ( 1527):     at d.a.c.a.j$a.a(Unknown Source:17)
I/flutter ( 1527):     at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
I/flutter ( 1527):     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
I/flutter ( 1527):     at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 1527):     at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter ( 1527):     at android.os.Looper.loop(Looper.java:183)
I/flutter ( 1527):     at android.app.ActivityThread.main(ActivityThread.java:7660)
I/flutter ( 1527):     at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 1527):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
I/flutter ( 1527):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter ( 1527):  )
I/flutter ( 1527): 
I/flutter ( 1527):  #0   StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
I/flutter ( 1527):  #1   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
I/flutter ( 1527):  #2   <asynchronous suspension>
I/flutter ( 1527):  #3   MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344)
I/flutter ( 1527):  #4   <asynchronous suspension>
I/flutter ( 1527):  #5   MadPay._invokeChannel (package:mad_pay/src/mad_pay.dart:27)
I/flutter ( 1527):  #6   <asynchronous suspension>
I/flutter ( 1527):  #7   MadPay._setEnvironment (package:mad_pay/src/mad_pay.dart:34)
```

Output of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale en-RU)
    • Flutter version 2.0.4 at /Users/svetozar/soft/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/svetozar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile)         • 99LAY1APNW    • android-arm64  • Android 11 (API 30)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by mit-73** [comment]
@Svet-00 Thank you for helping me [find this bug](https://github.com/protocolbuffers/protobuf/issues/6463). I updated the README.md (#12) and added the steps to follow to make it work properly. I also updated the example so that you can see it clearly.

Try this solution for yourself and if you do not have problems you can close the issue.

**Comment by Svet-00** [comment]
@mit-73 It works now. Thanks!
